package atoll

import (
	"bytes"
	"errors"
	"fmt"
	"math"
	"runtime"
	"unicode/utf8"
)

var (
	vowels     = [5]string{"a", "e", "i", "o", "u"}
	consonants = [21]string{
		"b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n",
		"p", "q", "r", "s", "t", "v", "w", "x", "y", "z",
	}
)

// letterEntropy is the entropy in bits of each letter generated by genRandWord.
//
// A vowel is picked with a probability of 4/11 and a consonant with 7/11, hence each
// one of the 5 vowels has a probability of 4/55 and each one of the 21 consonants of
// 1/33, making the entropy -Σ p·log2(p) = 4/11·log2(55/4) + 7/11·log2(33) ≈ 4.585.
var letterEntropy = (4.0/11.0)*math.Log2(55.0/4.0) + (7.0/11.0)*math.Log2(33.0)

const (
	noListType       = "NoList"
	wordListType     = "WordList"
	syllableListType = "SyllableList"
)

// maxWordRetries is the number of words tried before giving up when replacing an
// excluded word.
const maxWordRetries = 100

// Passphrase represents a sequence of words/syllables with a separator between them.
type Passphrase struct {
	// List used to generate the passphrase.
	List list
	// Words separator.
	Separator string
	words     [][]byte
	// err stores the errors occurred inside the list functions, as their signature
	// does not allow them to be returned.
	err error
	// Words that will be part of the passphrase.
	Include []string
	// Words that won't be part of the passphrase.
	Exclude []string
	// Number of words in the passphrase.
	Length uint64
}

type list func(p *Passphrase, length int)

// NewPassphrase returns a random passphrase.
func NewPassphrase(length uint64, l list) ([]byte, error) {
	p := &Passphrase{
		Length: length,
		List:   l,
	}

	return p.Generate()
}

// Generate generates a random passphrase.
func (p *Passphrase) Generate() ([]byte, error) {
	passphrase, err := p.generate()
	if err != nil {
		return nil, fmt.Errorf("atoll: %w", err)
	}

	return passphrase, nil
}

func (p *Passphrase) generate() ([]byte, error) {
	if err := p.validateParams(); err != nil {
		return nil, err
	}

	// Defaults
	if p.Separator == "" {
		p.Separator = " "
	}
	if p.List == nil {
		p.List = NoList
	}

	// Initialize secret slice
	p.words = make([][]byte, p.Length)
	p.err = nil
	length := int(p.Length) - len(p.Include)

	// Generate the passphrase with the list specified
	p.List(p, length)
	if p.err != nil {
		return nil, p.err
	}

	// Include and exclude words
	if len(p.Include) != 0 {
		if err := p.includeWords(); err != nil {
			return nil, err
		}
	}
	if len(p.Exclude) != 0 {
		if err := p.excludeWords(); err != nil {
			return nil, err
		}
	}

	passphrase := bytes.Join(p.words, []byte(p.Separator))
	// Wipe sensitive data. The words are copies owned by the passphrase, the lists
	// used to generate them are left untouched
	for i := range p.words {
		for j := range p.words[i] {
			p.words[i][j] = 0
		}
	}
	// Keep buf alive so preceding loop is not optimized out
	runtime.KeepAlive(p.words)
	return passphrase, nil
}

func (p *Passphrase) validateParams() error {
	if p.Length < 1 {
		return errors.New("passphrase length must be equal to or higher than 1")
	}

	if len(p.Include) > int(p.Length) {
		return errors.New("number of words to include exceed the password length")
	}

	// Look for 2/3 bytes characters
	if len(p.Separator) != utf8.RuneCountInString(p.Separator) {
		return fmt.Errorf("separator %q contains invalid characters", p.Separator)
	}

	for _, incl := range p.Include {
		// Look for words contaning 2/3 bytes characters
		if len(incl) != utf8.RuneCountInString(incl) {
			return fmt.Errorf("included word %q contains invalid characters", incl)
		}

		// Check for equality between included and excluded words
		for _, excl := range p.Exclude {
			if incl == excl {
				return fmt.Errorf("word %q cannot be included and excluded", excl)
			}
		}
	}

	return nil
}

// includeWords randomly inserts included words in the passphrase.
func (p *Passphrase) includeWords() error {
	// Add included words at the end of the secret
	for i, word := range p.Include {
		p.words[int(p.Length)-i-1] = []byte(word)
	}

	// Shuffle the secret so included words aren't always at the end
	for i := range p.words {
		j, err := randInt(i + 1)
		if err != nil {
			return err
		}

		p.words[i], p.words[j] = p.words[j], p.words[i]
	}

	return nil
}

// excludeWords checks if any excluded word is within the secret and (if true) replaces it
// with another random word.
func (p *Passphrase) excludeWords() error {
	excluded := make(map[string]struct{}, len(p.Exclude))
	for _, excl := range p.Exclude {
		excluded[excl] = struct{}{}
	}

	for i, word := range p.words {
		for retries := 0; ; retries++ {
			if _, ok := excluded[string(word)]; !ok {
				break
			}

			if retries == maxWordRetries {
				return fmt.Errorf("failed replacing the excluded word %q after %d attempts", word, maxWordRetries)
			}

			var err error
			if word, err = p.randWord(); err != nil {
				return err
			}

			p.words[i] = word
		}
	}

	return nil
}

// randWord returns a random word taken from the list used by the passphrase.
func (p *Passphrase) randWord() ([]byte, error) {
	list := p.List
	if list == nil {
		list = NoList
	}

	// Use the list to generate a single word so custom lists are supported as well
	aux := &Passphrase{
		List:      list,
		Separator: p.Separator,
		words:     make([][]byte, 1),
		Length:    1,
	}
	list(aux, 1)
	if aux.err != nil {
		return nil, aux.err
	}

	if len(aux.words[0]) == 0 {
		return nil, errors.New("the list provided did not generate any word")
	}

	return aux.words[0], nil
}

// setErr stores the first error occurred inside a list function.
func (p *Passphrase) setErr(err error) {
	if p.err == nil {
		p.err = err
	}
}

// Entropy returns the passphrase entropy in bits.
//
// Words that are included aren't taken into account: as the attacker is assumed to know
// the method used, they are fixed and known values that reduce the number of words that
// are randomly chosen.
//
// If the list used is "NoList" the secret must be already generated, if it's a custom
// one the pool of words is unknown and 0 is returned.
func (p *Passphrase) Entropy() float64 {
	// Included words are known, only the rest of them is randomly chosen
	random := int(p.Length) - len(p.Include)
	if random <= 0 {
		return 0
	}

	var poolLength int

	switch p.listName() {
	case noListType:
		if len(p.words) == 0 {
			return 0
		}

		// Words are joined without the separator, it isn't part of the secret entropy
		letters := 0
		for _, word := range p.words {
			letters += len(word)
		}
		// Discard the letters of the words that are known
		for _, incl := range p.Include {
			letters -= len(incl)
		}
		if letters <= 0 {
			return 0
		}

		return float64(letters) * letterEntropy
	case wordListType:
		poolLength = len(wordList)
	case syllableListType:
		poolLength = len(syllableList)
	default:
		// The number of words of a custom list cannot be determined
		return 0
	}

	// Excluded words are never part of the secret
	poolLength -= len(p.Exclude)
	if poolLength < 1 {
		return 0
	}

	return float64(random) * math.Log2(float64(poolLength))
}

// listName returns the name of the list used, defaulting to NoList like generate does.
func (p *Passphrase) listName() string {
	if p.List == nil {
		return noListType
	}

	return getFuncName(p.List)
}

// NoList generates a random passphrase without using a list, making the potential attacker work harder.
func NoList(p *Passphrase, length int) {
	for i := 0; i < length; i++ {
		word, err := genRandWord()
		if err != nil {
			p.setErr(err)
			return
		}

		p.words[i] = word
	}
}

// WordList generates a passphrase using a wordlist (18,325 long).
func WordList(p *Passphrase, length int) {
	for i := 0; i < length; i++ {
		idx, err := randInt(len(wordList))
		if err != nil {
			p.setErr(err)
			return
		}

		// Copy the word, the passphrase words are wiped after being joined
		p.words[i] = append([]byte(nil), wordList[idx]...)
	}
}

// SyllableList generates a passphrase using a syllable list (10,129 long).
func SyllableList(p *Passphrase, length int) {
	for i := 0; i < length; i++ {
		idx, err := randInt(len(syllableList))
		if err != nil {
			p.setErr(err)
			return
		}

		// Copy the syllable, the passphrase words are wiped after being joined
		p.words[i] = append([]byte(nil), syllableList[idx]...)
	}
}

// genRandWord returns a random word without using any list or dictionary.
func genRandWord() ([]byte, error) {
	var buf bytes.Buffer
	// Words length are randomly selected between 3 and 12 letters.
	n, err := randInt(10)
	if err != nil {
		return nil, err
	}

	wordLength := int(n) + 3
	buf.Grow(wordLength)

	for i := 0; i < wordLength; i++ {
		// Select a number from 0 to 10, 0-3 is a vowel, else a consonant
		class, err := randInt(11)
		if err != nil {
			return nil, err
		}

		if class <= 3 {
			idx, err := randInt(len(vowels))
			if err != nil {
				return nil, err
			}

			buf.WriteString(vowels[idx])
			continue
		}

		idx, err := randInt(len(consonants))
		if err != nil {
			return nil, err
		}

		buf.WriteString(consonants[idx])
	}

	return buf.Bytes(), nil
}
